services:
  - type: web
    name: recipeeAI
    runtime: node
    plan: free
    buildCommand: "npm install --prefix client && npm install --prefix server && npm run build --prefix client"
    startCommand: node server/server.js
    healthCheckPath: /api/health
    envVars:
      - key: NODE_VERSION
        value: 20.10.0
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: "mongodb+srv://Aditya:%402005%23AdiTYa@cluster0.nxedwck.mongodb.net/recipe-meal-planner"
      - key: MONGO_URI
        value: "mongodb+srv://Aditya:%402005%23AdiTYa@cluster0.nxedwck.mongodb.net/recipe-meal-planner"
      - key: JWT_SECRET
        generateValue: true
      - key: RENDER
        value: true
      - key: CLIENT_URL
        value: https://recipeeai.onrender.com
      - key: GEMINI_API_KEY
        sync: false
      - key: EMAIL_USER
        value: "singhaditya06.04.2005@gmail.com"
      - key: EMAIL_PASS
        sync: false
      - key: RECAPTCHA_SECRET
        sync: false
      - key: VITE_RECAPTCHA_SITE_KEY
        value: "6LeKOHYsAAAAABuAxhYuZZ_4e5uYmptmHvBe0XYx"
