services:
  - type: web
    name: recipe-meal-planner
    runtime: node
    plan: free
    buildCommand: npm run build
    startCommand: node server/server.js
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: RENDER
        value: true
      - key: CLIENT_URL
        value: https://recipeeai.onrender.com
      - key: GEMINI_API_KEY
        sync: false
      - key: EMAIL_USER
        value: "singhaditya06.04.2005@gmail.com"
      - key: EMAIL_PASS
        sync: false
      - key: RECAPTCHA_SECRET
        sync: false
      - key: VITE_RECAPTCHA_SITE_KEY
        value: "6LeKOHYsAAAAABuAxhYuZZ_4e5uYmptmHvBe0XYx"
